### ISSUE TITLE
Highlight find results more

### ISSUE THREAD

**Issue by vesauimonen** [michaelhelmick/flatland-dark#9]
The find results are currently very poorly visible. Consider adding more highlight to them, especially the current result. Here's an example styling:

```less
atom-text-editor::shadow .highlight.find-result .region {
  border: 1px lighten(#798188, 20%) solid;
}

atom-text-editor::shadow .highlight.current-result .region {
  border: 1px #fff solid;
  background: fade(#72aaca, 50%);
}
```

### Before
![screen shot 2015-03-05 at 21 36 51](https://cloud.githubusercontent.com/assets/1443031/6512916/e51b5918-c37f-11e4-84bd-2e4673c463a8.png)

### After
![screen shot 2015-03-05 at 21 38 34](https://cloud.githubusercontent.com/assets/1443031/6512946/0df188f8-c380-11e4-8484-d47af1fc32f9.png)
